version: '3'
services:
  # hyperf
  hyperf:
    image: hyperf/hyperf:${HYPERF_VERSION}
    hostname: hyperf
    container_name: hyperf-compose
    restart: always
    privileged: true
    ports:
      - '${HYPERF_HOST_PORT}:9501'
    links:
      - mysql
      - redis
#      - phpmyadmin
#      - rabbitmq
#      - memcached
    volumes:
      - ${HYPERF_WORK_DIR}:/data/project/
    tty: true
    networks:
      - hyperf_networks

  # mysql
  mysql:
    container_name: zh_mysql
    hostname: mysql
    image: mysql:${MYSQL_VERSION}
    privileged: true
    expose:
      - "3306"
    ports:
      - '${MYSQL_HOST_PORT}:3306'
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - hyperf_networks

  # redis
  redis:
    container_name: zh_redis
    hostname: redis
    image: redis:${REDIS_VERSION}
    ports:
      - '${REDIS_HOST_PORT}:6379'
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis/redis.conf
      - ${REDIS_DATA_DIR}:/data
    restart: always
    entrypoint: ['redis-server', '/etc/redis/redis.conf']
    networks:
      - hyperf_networks

networks:
  hyperf_networks:
